server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: chuncker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: chuncker
          app: chuncker
          env: development
          __path__: /var/log/chuncker/*.log

  - job_name: chuncker-json-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: chuncker-json
          app: chuncker
          env: development
          __path__: /var/log/chuncker/*.json
          
  - job_name: mongodb-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mongodb-logs
          app: chuncker
          env: development
          source: mongodb
          __path__: /var/log/chuncker/mongodb-logs/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: Timestamp
            level: Level
            message: RenderedMessage
            exception: Exception
            source_context: SourceContext
            correlation_id: Properties.CorrelationId
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.0000000Z"
      - labels:
          level:
          source_context:
          correlation_id:
